#Clases, Herencias y polimorfismos

## Definiciones
Se usa `def` para declarar


In [6]:
#Vamos a crear una definicion (que es una funcion integrada en python)

def Isexy (a,b,c):
  x = a+b*c
  return x

In [7]:
Isexy (23,45,67)

3038

In [16]:
# Vamos a crear una definicion que calcule la inversa de una matriz
import numpy as np

def Inv_Isexy (M):
  x=np.linalg.inv(M)
  return x

In [22]:
import random
rannum = round(random.random(), 2)
rannum

0.26

In [23]:
a = round(random.random(), 2)

In [24]:
b = round(random.random(), 2)

In [25]:
c= round(random.random(), 2)

In [26]:
d= round(random.random(), 2)

In [27]:
e= round(random.random(), 2)

In [28]:
f= round(random.random(), 2)

In [29]:
g= round(random.random(), 2)

In [30]:
h= round(random.random(), 2)

In [31]:
i= round(random.random(), 2)

In [37]:
Isexynormy=np.array(([a,b,c],[d,e,f],[g,h,i]))

In [38]:
Isexynormy

array([[0.59, 0.  , 0.45],
       [0.83, 0.84, 0.48],
       [0.86, 0.62, 0.34]])

In [39]:
Inv_Isexy(Isexynormy)

array([[ 0.11929615, -2.77363555,  3.75782881],
       [-1.2983398 ,  1.85306691, -0.89770355],
       [ 2.06581171,  3.63654439, -4.92693111]])

In [40]:
y=np.random.randint(1,20,size=(2,2))
Inv_Isexy(y)

array([[ 0.06642066, -0.00369004],
       [-0.06273063,  0.05904059]])

In [41]:
y

array([[16,  1],
       [17, 18]])